
image:
  repository: ghcr.io/emiakia/flask-app:v01
  tag: v01
service:
  type: NodePort #LoadBalancer
  port: 5000
serviceAccount:
  create: false
  name: ""
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: flask-app.local 
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
