apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: ghcr.io/emiakia/flask-app-helm:v01
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: ghcr-secret  # Reference to the image pull secret
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30001  # Optional; can be omitted for automatic assignment
  selector:
    app: flask-app

